name = "Boys and the Hoods"
author = "Sehnryr"
version = "0.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2191cde60020b9e024c23ae71d83be23ce3ba91701911458964d70b05f808d3a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
