name = "Boys and the Hoods"
author = "Sehnryr"
version = "0.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0badb7534b4bb966605385f2bd1bb0f3a81c7cb01afdfbb56acff544e134b35f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
