[general]
	"Enable 'q' Button" = false

[categories]
	automation = false
	building = false
	management = true
	tools = true
	tweaks = false
	world = false
	mobs = false
	client = false
	experimental = false
	oddities = false

[management]
	"Automatic Tool Restock" = false
	"Easy Transferring" = false
	"Expanded Item Interactions" = false
	"Hotbar Changer" = false
	"Inventory Sorting" = true
	"Item Sharing" = false
	"Quick Armor Swapping" = false

[tools]
	Abacus = false
	"Ambient Discs" = false
	"Ancient Tomes" = false
	"Beacon Redirection" = false
	"Bottled Cloud" = false
	"Color Runes" = false
	"Endermosh Music Disc" = false
	"Parrot Eggs" = false
	"Pathfinder Maps" = false
	Pickarang = false
	"Seed Pouch" = false
	"Skull Pikes" = false
	"Slime In A Bucket" = false
	"Torch Arrow" = false
	Trowel = true
